<?php
/**
 * TransformationDescriptor
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Cloudinary\MediaEditing
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Cloudinary Media Editing API
 *
 * Cloudinary Media Editing API
 *
 * The version of the OpenAPI document: 0.1.0-beta
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Cloudinary\MediaEditing\Model;

use \ArrayAccess;
use \Cloudinary\MediaEditing\ObjectSerializer;

/**
 * TransformationDescriptor Class Doc Comment
 *
 * @category Class
 * @package  Cloudinary\MediaEditing
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class TransformationDescriptor implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'TransformationDescriptor';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'descriptor_type' => 'string',
        'named_transformation' => 'string',
        'canonical_transformation' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'descriptor_type' => null,
        'named_transformation' => null,
        'canonical_transformation' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'descriptor_type' => 'descriptor_type',
        'named_transformation' => 'named_transformation',
        'canonical_transformation' => 'canonical_transformation'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'descriptor_type' => 'setDescriptorType',
        'named_transformation' => 'setNamedTransformation',
        'canonical_transformation' => 'setCanonicalTransformation'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'descriptor_type' => 'getDescriptorType',
        'named_transformation' => 'getNamedTransformation',
        'canonical_transformation' => 'getCanonicalTransformation'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const DESCRIPTOR_TYPE_CANONICAL = 'canonical';
    public const DESCRIPTOR_TYPE_NAMED = 'named';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getDescriptorTypeAllowableValues()
    {
        return [
            self::DESCRIPTOR_TYPE_CANONICAL,
            self::DESCRIPTOR_TYPE_NAMED,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['descriptor_type'] = $data['descriptor_type'] ?? null;
        $this->container['named_transformation'] = $data['named_transformation'] ?? null;
        $this->container['canonical_transformation'] = $data['canonical_transformation'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['descriptor_type'] === null) {
            $invalidProperties[] = "'descriptor_type' can't be null";
        }
        $allowedValues = $this->getDescriptorTypeAllowableValues();
        if (!is_null($this->container['descriptor_type']) && !in_array($this->container['descriptor_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'descriptor_type', must be one of '%s'",
                $this->container['descriptor_type'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets descriptor_type
     *
     * @return string
     */
    public function getDescriptorType()
    {
        return $this->container['descriptor_type'];
    }

    /**
     * Sets descriptor_type
     *
     * @param string $descriptor_type The type of transformation to use
     *
     * @return self
     */
    public function setDescriptorType($descriptor_type)
    {
        $allowedValues = $this->getDescriptorTypeAllowableValues();
        if (!in_array($descriptor_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'descriptor_type', must be one of '%s'",
                    $descriptor_type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['descriptor_type'] = $descriptor_type;

        return $this;
    }

    /**
     * Gets named_transformation
     *
     * @return string|null
     */
    public function getNamedTransformation()
    {
        return $this->container['named_transformation'];
    }

    /**
     * Sets named_transformation
     *
     * @param string|null $named_transformation The name of a previously saved transformation
     *
     * @return self
     */
    public function setNamedTransformation($named_transformation)
    {
        $this->container['named_transformation'] = $named_transformation;

        return $this;
    }

    /**
     * Gets canonical_transformation
     *
     * @return string|null
     */
    public function getCanonicalTransformation()
    {
        return $this->container['canonical_transformation'];
    }

    /**
     * Sets canonical_transformation
     *
     * @param string|null $canonical_transformation A set of transformation parameters defined using Cloudinary URL syntax
     *
     * @return self
     */
    public function setCanonicalTransformation($canonical_transformation)
    {
        $this->container['canonical_transformation'] = $canonical_transformation;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


