<?php
/**
 * MediaConnectorInstanceTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Cloudinary
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Cloudinary Media Editing API
 *
 * Cloudinary Media Editing API
 *
 * The version of the OpenAPI document: 0.1.0-beta
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Cloudinary\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * MediaConnectorInstanceTest Class Doc Comment
 *
 * @category    Class
 * @description MediaConnectorInstance
 * @package     Cloudinary
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class MediaConnectorInstanceTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "MediaConnectorInstance"
     */
    public function testMediaConnectorInstance()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "fwd_key"
     */
    public function testPropertyFwdKey()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "template_variables"
     */
    public function testPropertyTemplateVariables()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
